#! /bin/sh

if [ $# != 1 ]
then
    echo "usage: mkqr signid"
    exit 1
fi

signid=$1

# smallest style qr code can hold (upper case alpha, numeric, a few symbols):
# 25 chars at level L
# 20 chars at level M
# 16 chars at level Q
# 10 chars at level H


# with 4 digit signid, this is 20 chars
qrmsg="HTTP://BOSHW.US/$signid"
url_label="http://BosHW.us/$signid"

outname=qr${signid}.png

cellsize=120

f_core=TMP.core.png
f_grid=TMP.grid.png
f_url_label=TMP.url_label.png
f_more=TMP.more.png

qrencode -o $f_core --margin=0 --size=${cellsize} --level=M --type=PNG "$qrmsg"
qrencode -o $f_grid            --size=${cellsize} --level=M --type=PNG "$qrmsg"

core_width=`convert $f_core -format "%w" info:`
grid_width=`convert $f_grid -format "%w" info:`

url_pointsize=`convert \
	-size "$core_width" \
	-font Courier-Bold \
 	label:"$url_label" \
	-format '%[label:pointsize]' \
	info:`
url_h=`convert -size "$core_width" -font Courier-Bold label:"$url_label" \
	-format '%h' info:`

url_h=`expr $url_h + 6`

convert -size ${core_width}x${url_h} -gravity center -pointsize $url_pointsize \
	-font Courier-Bold label:"$url_label" $f_url_label


convert -pointsize $url_pointsize \
	-size x${url_h} \
	-font NewCenturySchlbk-Italic \
	label:"   , en español, & more" $f_more

# was 288 high
s=SmallSpeakerImage-296643-openclipart.png
convert -flatten $s -resize '40%' TMP.s1.png
convert -size 1x40 xc:white TMP.s2.png
convert -append TMP.s2.png TMP.s1.png TMP.s3.png


convert -size 20x20 xc:white TMP.space.png
convert +append TMP.s3.png TMP.space.png $f_more TMP.speaker.png

convert -size 20x30 xc:white TMP.space2.png
convert -size 20x50 xc:white TMP.space3.png

convert $f_grid $f_url_label TMP.space2.png TMP.speaker.png TMP.space3.png -gravity center -append $outname

echo "output in $outname"
